"""Add follows table and user follow relationships

Revision ID: bf46f586d627
Revises: f123456789ab
Create Date: 2025-07-21 10:49:48.670834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf46f586d627'
down_revision = 'f123456789ab'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'follows',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('follower_id', sa.Integer(), nullable=False),
        sa.Column('followed_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['follower_id'], ['users.id']),
        sa.ForeignKeyConstraint(['followed_id'], ['users.id']),
        sa.UniqueConstraint('follower_id', 'followed_id', name='unique_follow')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
