"""Add profile fields to User model

Revision ID: d90faf2ee70e
Revises: e29f1a9d2d84
Create Date: 2025-06-25 17:39:32.882018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90faf2ee70e'
down_revision = 'e29f1a9d2d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('instagram')
        batch_op.drop_column('twitter')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
