"""add elapsed_time to activities

Revision ID: e354f1dcc440
Revises: bf46f586d627
Create Date: 2025-07-22 13:32:33.591202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e354f1dcc440'
down_revision = 'bf46f586d627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elapsed_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('elapsed_time')

    # ### end Alembic commands ###
